"merge into master":
  - base-branch: master
"merge into release":
  - base-branch: release
frontend:
  - changed-files: ["client/**", "app/javascript/**"]
# "skip jenkins":
#   - changed-files:
#       - all: ["!**/*.rb", "!**/*.erb", "!config/locales/**/*"]
feature:
  - head-branch: ["^feature/", "^feat/"]
enhance:
  - head-branch: ["^enhancement/", "^enhance/"]
bug:
  - head-branch: ["^bug/", "^fix/"]
chore:
  - head-branch: "^chore/"
test:
  - head-branch: "^test/"
