"merge into master":
  - base-branch: master
"merge into release":
  - base-branch: release
feature:
  - head-branch: ["^feature/", "^feat/"]
enhance:
  - head-branch: ["^enhancement/", "^enhance/"]
bug:
  - head-branch: ["^bug/", "^fix/"]
chore:
  - head-branch: "^chore/"
test:
  - head-branch: "^test/"
frontend:
  - all:
      - head-branch: ["test/test8"]
      - changed-files:
          - client/**/*
          - app/javascript/**/*
          - app/assets/javascripts/**/*
          - spec/javascript/**/*
          - config/webpack/**/*
          - config/webpacker.yml
          - babel.config.js
          - jest.config.js
          - postcss.config.js
          - relay.config.js
          - jsconfig.json
          - yarn.lock
          - package.json
          - .eslintrc.yml
          - .eslintignore
          - .prettierrc.yml
          - .prettierignore
          - .autocorrectignore

"wait other branches":
  - all:
      - base-branch: ["^(?!develop$)", "^(?!release$)", "^(?!master$)"]
