"merge into master":
  - base-branch: master
"merge into release":
  - base-branch: release
frontend:
  - changed-files:
      - client/**
      - app/javascript/**
      # - any:
      #     [
      #       "app/assets/javascripts/**",
      #       "!app/assets/javascripts/map/main_canvas/image_path/**",
      #       "!app/assets/javascripts/map/main_canvas/cell_layers_manager.js.erb",
      #     ]
      # - spec/javascript/**
      # - config/webpack/**
      # - config/webpacker.yml
      # - babel.config.js
      # - jest.config.js
      # - postcss.config.js
      # - relay.config.js
      # - jsconfig.json
      # - yarn.lock
      # - package.json
      # - .eslintrc.yml
      # - .eslintignore
      # - .prettierrc.yml
      # - .prettierignore
      # - .autocorrectignore
# "skip jenkins":
#   - changed-files:
#       - all: ["!**/*.rb", "!**/*.erb", "!config/locales/**/*"]
feature:
  - head-branch: ["^feature/", "^feat/"]
enhance:
  - head-branch: ["^enhancement/", "^enhance/"]
bug:
  - head-branch: ["^bug/", "^fix/"]
chore:
  - head-branch: "^chore/"
test:
  - head-branch: "^test/"
