feature:
  - head-branch: ["^feature/", "^feat/"]
enhance:
  - head-branch: ["^enhancement/", "^enhance/"]
bug:
  - head-branch: ["^bug/", "^fix/"]
chore:
  - head-branch: "^chore/"
test:
  - head-branch: "^test/"

frontend:
  - all:
      - head-branch: ["!test/test7", "!develop"]
      - changed-files:
          - client/**
          - app/javascript/**
          - spec/javascript/**
          - config/webpack/**
          - config/webpacker.yml
          - babel.config.js
          - jest.config.js
          - postcss.config.js
          - relay.config.js
          - jsconfig.json
          - yarn.lock
          - package.json
          - .eslintrc.yml
          - .eslintignore
          - .prettierrc.yml
          - .prettierignore
          - .autocorrectignore

"skip jenkins":
  - all:
      - changed-files: ["!**/*.rb", "!config/locales/**/*"]
