name: Add labels to pull requests

on:
  workflow_call:

jobs:
  triage:
    # permissions:
    #   contents: read
    #   pull-requests: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/labeler@v4
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          configuration-path: ".github/labeler.yml"
          sync-labels: false
          dot: false
