name: Pull Request Labeler
on:
  pull_request:
    types:
      - opened
      - synchronize
jobs:
  add_labels:
    permissions:
      contents: read
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/labeler@v4
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          configuration-path: ".github/labeler.yml"
          sync-labels: false
