name: Add labels to pull requests

on:
  pull_request:
    types: [opened, reopened, synchronize, edited, ready_for_review]

jobs:
  if: ${{ github.event.action == 'edited' }}
  triage:
    permissions:
      contents: read
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Label PRs
        uses: actions/labeler@v5.0.0-alpha.1
        with:
          configuration-path: ".github/labeler.yml"
          sync-labels: true
