name: Add labels to pull requests

on:
  pull_request_target:
    types: [opened, reopened, synchronize, ready_for_review]

jobs:
  triage:
    permissions:
      contents: read
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Label PRs based on the paths of changed files
        uses: actions/labeler@v4
        with:
          configuration-path: ".github/labeler.yml"
          sync-labels: false
      - name: Label PRs based on branch name patterns
        uses: TimonVS/pr-labeler-action@v4
        with:
          configuration-path: ".github/pr-labeler.yml"
      - name: Label PRs based on head branch
      - uses: actions/labeler@v4
        if: ${{ github.base_ref == 'main'}}
        width:
          configuration-path: ".github/config/labeler.yml"
