name: Add labels to pull requests

on:
  pull_request_target:
    types: [opened, reopened, ready_for_review]

jobs:
  triage:
    permissions:
      contents: read
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/labeler@v4
        with:
          configuration-path: ".github/labeler.yml"
          sync-labels: false
      - uses: TimonVS/pr-labeler-action@v4
        with:
          configuration-path: ".github/pr-labeler.yml"
