name: Label PR based on Title

on:
  pull_request:
    types:
      - opened
      - synchronize

jobs:
  label-pr:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Set PR Title
        id: pr_title
        run: echo "PR_TITLE=$(jq -r .pull_request.title $GITHUB_EVENT_PATH)" >> $GITHUB_ENV

      - name: Run Label Script
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_REPOSITORY_OWNER: ${{ github.repository_owner }}
          GITHUB_REPOSITORY: ${{ github.repository }}
          PR_TITLE: ${{ env.PR_TITLE }}
          PR_NUMBER: ${{ github.event.pull_request.number }}
        run: node .github/label-pr.js
