name: Add Labels

on:
  pull_request:
    type:
      - opened
      - edited
      - synchronize

jobs:
  add_labels:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: add labels
        run: |
          console.log('hi');
