name: Add Labels

on:
  pull_request:
    type:
      - opened
      - edited
      - synchronize

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "14" # 使用 Node.js 的版本

      - name: Run My Node.js Script
        run: node ../myscript.js
